name: terraform_core

on:
  push:
    branches:
      - main
    paths:
      - core/**
  pull_request:
    paths:
      - core/**
  workflow_dispatch:
    inputs:
      OPA_BLAST_RADIUS:
        description: OPA Blast Radius
        required: true
        default: "50"

jobs:
  terraform:
    uses: xenitab/azure-devops-templates/.github/workflows/terraform-docker.yaml@2021.09.3
    with:
      DIR: core
      ENVIRONMENTS: |
        {
          "environments":[
            {"name":"dev"},
            {"name":"qa"}
          ]
        }
    secrets:
      AZ_APP_ID: ${{ secrets.AZ_APP_ID }}
      AZ_APP_SECRET: ${{ secrets.AZ_APP_SECRET }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      SUB_IDS: '{"dev": "${{ secrets.SUBSCRIPTION_ID_DEV }}", "qa": "${{ secrets.SUBSCRIPTION_ID_QA }}"}'
