parameters:
  - name: poolName
    type: string
    default: ""
  - name: environment
    type: string
    default: ""
  - name: serviceName
    type: string
    default: ""
  - name: sourceBranch
    type: string
    default: ""
  - name: deployTags
    type: boolean
    default: false
  - name: imageTagPath
    type: string
    default: ""
  - name: binaries
    type: object
    default:
      fluxStatus:
        tag: "v0.2.0"
        sha: "024b38bd62e432683d3560ce54718597c51af17f377804ddc26f01ed840b435e"
      jq:
        tag: "jq-1.6"
        sha: "af986793a515d500ab2d35f8d2aecd656e764504b789b66d7e1a0b727a124c44"

jobs:
  - deployment: deploy_${{ parameters.environment }}
    timeoutInMinutes: 20
    condition: and(succeeded(), or(and(eq(variables['resources.pipeline.ciPipeline.sourceBranch'], '${{ parameters.sourceBranch }}'), eq(${{ parameters.deployTags }}, false)), and(startsWith(variables['resources.pipeline.ciPipeline.sourceBranch'], 'refs/tags/'), eq(${{ parameters.deployTags }}, true))))
    displayName: Deploy to ${{ parameters.environment }}
    pool:
      name: ${{ parameters.poolName }}
    continueOnError: false
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              displayName: Get sources
              persistCredentials: true

            - bash: |
                set -e
                IMAGE_TAG=${SOURCE_VERSION:0:7}
                echo "##vso[task.setvariable variable=imageTag]$IMAGE_TAG"
              displayName: "Create image id"
              env:
                SOURCE_VERSION: $(resources.pipeline.ciPipeline.sourceCommit)

            - bash: |
                set -ex
                pip3 install yq

                git checkout master
                git pull
                git fetch -p
                git reset --hard origin/master
                git config --global user.email "azure-pipelines@${PROJECT_NAME}.${REPO_NAME}"
                git config --global user.name "Azure Pipelines (${PROJECT_NAME} ${REPO_NAME})"
                git status

                CURRENT_TAG=$(yq -r "${TAG_PATH}" ${ENV}/${SERVICE_NAME}.yaml)
                if [ "${CURRENT_TAG}" == "${NEW_TAG}" ]; then
                  echo "Image tag for ${ENV}/${SERVICE_NAME}.yaml is already ${NEW_TAG}"
                  exit 0
                fi

                echo "Changing image tag from ${CURRENT_TAG} to ${NEW_TAG} for ${ENV}/${SERVICE_NAME}.yaml"
                yq --in-place -Y "${TAG_PATH}=\"${NEW_TAG}\"" ${ENV}/${SERVICE_NAME}.yaml
                git add ${ENV}/${SERVICE_NAME}.yaml
                git status
                git commit -m "${ENV}/${SERVICE_NAME}.yaml - changed image tag from ${CURRENT_TAG} to ${NEW_TAG}"
                git push origin
              displayName: "Change image in GitOps repo"
              env:
                ENV: ${{ parameters.environment }}
                SERVICE_NAME: ${{ parameters.serviceName }}
                NEW_TAG: $(imageTag)
                TAG_PATH: ${{ parameters.imageTagPath }}
                PROJECT_NAME: $(System.TeamProject)
                REPO_NAME: $(Build.Repository.Name)

            - bash: |
                set -ex
                pip3 install yq
                wget https://github.com/XenitAB/flux-status/releases/download/${FLUX_STATUS_CLI_TAG}/flux-status-cli
                DOWNLOAD_FLUX_STATUS_CLI_SHA=$(openssl sha1 -sha256 flux-status-cli | awk '{print $2}')
                if [[ "${FLUX_STATUS_CLI_SHA}" != "${DOWNLOAD_FLUX_STATUS_CLI_SHA}" ]]; then
                    echo "Downloaded checksum (${DOWNLOAD_FLUX_STATUS_CLI_SHA}) for flux-status-cli does not match expected value: ${FLUX_STATUS_CLI_SHA}"
                    exit 1
                fi
                chmod +x flux-status-cli
                mv flux-status-cli /usr/bin/
                wget https://github.com/stedolan/jq/releases/download/${JQ_TAG}/jq-linux64
                DOWNLOAD_JQ_SHA=$(openssl sha1 -sha256 jq-linux64 | awk '{print $2}')
                if [[ "${JQ_SHA}" != "${DOWNLOAD_JQ_SHA}" ]]; then
                    echo "Downloaded checksum (${DOWNLOAD_JQ_SHA}) for jq-linux64 does not match expected value: ${JQ_SHA}"
                    exit 1
                fi
                mv jq-linux64 jq
                chmod +x jq
                mv jq /usr/bin/

                git checkout master
                git pull
                git fetch -p
                git reset --hard origin/master
                git config --global user.email "azure-pipelines@${PROJECT_NAME}.${REPO_NAME}"
                git config --global user.name "Azure Pipelines (${PROJECT_NAME} ${REPO_NAME})"
                git status

                while true; do
                  sleep 5

                  git pull origin master
                  CURRENT_TAG=$(yq -r "${TAG_PATH}" ${ENV}/${SERVICE_NAME}.yaml)
                  if [ "${CURRENT_TAG}" != "${NEW_TAG}" ]; then
                    echo "Image tag for ${ENV}/${SERVICE_NAME}.yaml is no longer the expected value ${NEW_TAG}"
                    exit 1
                  fi

                  COMMIT_ID=$(git rev-list -1 HEAD -- $ENV)

                  set +e
                  RESULT=$(flux-status-cli --instance ${ENV} --action workload  --git-url ${REPO_URI} --azdo-pat ${TOKEN} --commit-id ${COMMIT_ID})
                  if [ $? -ne 0 ]; then
                    echo $RESULT
                    continue
                  fi
                  set -e

                  STATE=$(echo $RESULT | jq -r .state)
                  echo "Commit status is $STATE"
                  if [ $STATE == "succeeded" ]; then
                    exit 0
                  elif [[ $STATE == "failed" || $STATE == "canceled" ]]; then
                    exit 1
                  fi
                done
              displayName: Wait for ${{ parameters.environment }}
              env:
                ENV: ${{ parameters.environment }}
                SERVICE_NAME: ${{ parameters.serviceName }}
                NEW_TAG: $(imageTag)
                TAG_PATH: ${{ parameters.imageTagPath }}
                PROJECT_NAME: $(System.TeamProject)
                REPO_NAME: $(Build.Repository.Name)
                REPO_URI: $(Build.Repository.Uri)
                TOKEN: $(System.AccessToken)
                FLUX_STATUS_CLI_TAG: ${{ parameters.binaries.fluxStatus.tag }}
                FLUX_STATUS_CLI_SHA: ${{ parameters.binaries.fluxStatus.sha }}
                JQ_TAG: ${{ parameters.binaries.jq.tag }}
                JQ_SHA: ${{ parameters.binaries.jq.sha }}
