parameters:
  - name: poolNameTemplate
    type: string
    default: ""
  - name: poolVmImage
    type: string
    default: "ubuntu-18.04"
  - name: sourceBranch
    type: string
    default: "refs/heads/master"
  - name: environments
    type: object
    default:
      - name: dev
      - name: qa
      - name: prod
  - name: azureSubscriptionTemplate
    type: string
  - name: terraformFolder
    type: string
stages:
  - stage: plan
    jobs:
      - ${{ each env in parameters.environments }}:
          - job: ${{ env.name }}
            pool:
              ${{ if not(eq(parameters.poolNameTemplate, '')) }}:
                name: ${{ format(parameters.poolNameTemplate, env.name) }}
              ${{ if not(eq(parameters.poolVmImage, '')) }}:
                vmImage: ${{ parameters.poolVmImage }}
            steps:
              - task: AzureCLI@1
                inputs:
                  azureSubscription: ${{ format(parameters.azureSubscriptionTemplate, env.name) }}
                  addSpnToEnvironment: true
                  scriptLocation: inlineScript
                  inlineScript: |
                    if [ -n "${OPA_BLAST_RADIUS}" ] && [ "${OPA_BLAST_RADIUS}" -eq "${OPA_BLAST_RADIUS}" ] 2>/dev/null; then
                      echo OPA_BLAST_RADIUS: ${OPA_BLAST_RADIUS}
                    else
                      export OPA_BLAST_RADIUS=50
                      echo OPA_BLAST_RADIUS: ${OPA_BLAST_RADIUS}
                    fi

                    # pre-azdo
                    set -e
                    AZURE_CONFIG_DIR="${AZURE_CONFIG_DIR:-${HOME}/.azure}"
                    mkdir -p ${PWD}/${DIR}/.terraform/
                    echo ARM_CLIENT_ID=${servicePrincipalId} > ${PWD}/${DIR}/.terraform/${ENV}.env
                    echo ARM_CLIENT_SECRET=${servicePrincipalKey} >> ${PWD}/${DIR}/.terraform/${ENV}.env
                    echo ARM_TENANT_ID=${tenantId} >> ${PWD}/${DIR}/.terraform/${ENV}.env
                    echo ARM_SUBSCRIPTION_ID=$(az account show -o tsv --query 'id') >> ${PWD}/${DIR}/.terraform/${ENV}.env
                    set +e
                    sudo chown -R 1000:1000 ${PWD}/${DIR}
                    sudo chown -R 1000:1000 ${AZURE_CONFIG_DIR}
                    sudo chown -R 1000:1000 ${PWD}/global.tfvars

                    make prepare
                    PREPARE_ERROR_CODE=$?
                    if [[ ${PREPARE_ERROR_CODE} = 0 ]]; then
                      make plan
                      PLAN_ERROR_CODE=$?
                    fi

                    # post-azdo
                    sudo chown -R $(id -u):$(id -g) ${PWD}/${DIR}
                    sudo chown -R $(id -u):$(id -g) ${AZURE_CONFIG_DIR}
                    sudo chown -R $(id -u):$(id -g) ${PWD}/global.tfvars

                    if [[ ${PREPARE_ERROR_CODE} != 0 ]]; then
                      echo "ERROR: PREPARE failed."
                      exit ${PREPARE_ERROR_CODE}
                    elif [[ ${PLAN_ERROR_CODE} != 0 ]]; then
                      echo "ERROR: PLAN failed."
                      exit ${PLAN_ERROR_CODE}
                    else
                      echo "INFO: Both PREPARE and PLAN completed successfully."
                      exit 0
                    fi
                env:
                  DIR: ${{ parameters.terraformFolder }}
                  ENV: ${{ env.name }}
                  OPA_BLAST_RADIUS: $(opaBlastRadius)
                displayName: "Terraform Plan"

              - task: PublishPipelineArtifact@0
                inputs:
                  targetPath: $(Build.Repository.LocalPath)/${{ parameters.terraformFolder }}/.terraform/plans
                  artifactName: "${{ env.name }}.enc"
                displayName: "Publish artifact"
