parameters:
  - name: poolNameTemplate
    type: string
    default: ""
  - name: poolVmImage
    type: string
    default: "ubuntu-18.04"
  - name: sourceBranch
    type: string
    default: "refs/heads/master"
  - name: environments
    type: object
    default:
      - name: dev
      - name: qa
      - name: prod
  - name: azureSubscriptionTemplate
    type: string
  - name: terraformFolder
    type: string
stages:
  - stage: plan
    jobs:
      - ${{ each env in parameters.environments }}:
          - job: ${{ env.name }}
            pool:
              ${{ if not(eq(parameters.poolNameTemplate, '')) }}:
                name: ${{ format(parameters.poolNameTemplate, env.name) }}
              ${{ if not(eq(parameters.poolVmImage, '')) }}:
                vmImage: ${{ parameters.poolVmImage }}
            steps:
              - task: AzureCLI@1
                inputs:
                  azureSubscription: ${{ format(parameters.azureSubscriptionTemplate, env.name) }}
                  addSpnToEnvironment: true
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -e
                    ARM_SUBSCRIPTION_ID=$(az account show -o tsv --query 'id') make pre-azdo
                    make prepare
                    make plan
                    make post-azdo
                env:
                  DIR: ${{ parameters.terraformFolder }}
                  ENV: ${{ env.name }}
                displayName: "Terraform Plan"

              - task: PublishPipelineArtifact@0
                inputs:
                  targetPath: $(Build.Repository.LocalPath)/${{ parameters.terraformFolder }}/.terraform/plans
                  artifactName: "${{ env.name }}.enc"
                displayName: "Publish artifact"
