parameters:
  - name: poolVmImage
    type: string
    default: "ubuntu-16.04"
  - name: poolName
    type: string
    default: ""
  - name: environment
    type: string
  - name: azureSubscription
    type: string
  - name: serviceName
    type: string
  - name: acrName
    type: string
  - name: imagePathPrefix
    type: string
    default: ""
  - name: extraTag
    type: string
    default: ""
  - name: gitopsPromotionTag
    type: string
    default: "v0.0.1"
  - name: group
    type: string
  - name: pipelines
    type: object
    default: []
  - name: tag
    type: string

jobs:
  - job: New
    pool:
      ${{ if not(eq(parameters.poolName, '')) }}:
        name: ${{ parameters.poolName }}
      ${{ if not(eq(parameters.poolVmImage, '')) }}:
        vmImage: ${{ parameters.poolVmImage }}
    steps:
      - checkout: self
        persistCredentials: true
        displayName: Get sources
      - bash: |
          echo ${TAG}
        env:
          TAG: ${{ parameters.tag }}
        displayName: Debug
  #- template: ./push.yaml
  #  parameters:
  #    environment: ${{ parameters.environment }}
  #    serviceName: ${{ parameters.serviceName }}
  #    azureSubscription: ${{ parameters.azureSubscription }}
  #    acrName: ${{ parameters.acrName }}
  #    imagePathPrefix: ${{ parameters.imagePathPrefix }}
  #    pipelines: ${{ parameters.pipelines }}
  #- template: ./new.yaml
  #  parameters:
  #    gitopsPromotionTag: ${{ parameters.gitopsPromotionTag }}
  #    group: ${{ parameters.group }}
  #    pipelines: ${{ parameters.pipelines }}
