parameters:
  - name: poolVmImage
    type: string
    default: "ubuntu-16.04"
  - name: poolName
    type: string
    default: ""
  - name: gitopsPromotionTag
    type: string
  - name: group
    type: string

jobs:
  - job: New
    pool:
      ${{ if not(eq(parameters.poolName, '')) }}:
        name: ${{ parameters.poolName }}
      ${{ if not(eq(parameters.poolVmImage, '')) }}:
        vmImage: ${{ parameters.poolVmImage }}
    steps:
      - checkout: self
        persistCredentials: true
        displayName: Get sources
      - bash: |
          set -e
          SOURCE_VERSION_KEY="RESOURCES_PIPELINE_${SERVICE_NAME^^}_SOURCECOMMIT"
          SOURCE_VERSION=$(env | grep -e "^${SOURCE_VERSION_KEY}" | cut -d= -f2)
          echo "##vso[task.setvariable variable=tag]${SOURCE_VERSION:0:7}"
        displayName: "Calculate artifact variables"
        env:
          SERVICE_NAME: $(resources.triggeringAlias)
      - bash: |
          git config --global user.email "azure-pipelines@${PROJECT_NAME}.${REPO_NAME}"
          git config --global user.name "Azure Pipelines (${PROJECT_NAME} ${REPO_NAME})"
          docker run -v $(pwd):/workspace ghcr.io/xenitab/gitops-promotion:${GITOPS_PROMOTION_TAG} new --token ${TOKEN} --group ${GROUP} --app ${APP} --tag ${TAG:0:7}
        env:
          GITOPS_PROMOTION_TAG: ${{ parameters.gitopsPromotionTag }}
          PROJECT_NAME: $(System.TeamProject)
          REPO_NAME: $(Build.Repository.Name)
          TOKEN: $(System.AccessToken)
          GROUP: ${{ parameters.group }}
          APP: $(resources.triggeringAlias)
          TAG: $(tag)
          USER_IDENTITY: $(Build.RequestedForId)
        displayName: GitOps Promotion
