name: update-from-upstream

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:
  pull_request:

jobs:
  update-from-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Update from upstream
        uses: actions/checkout@v2
        # this makes no sense to run on the main repository, so disable
        # it there
        if: ${{ env.GITHUB_REPOSITORY != 'XenitAB/azure-devops-templates' }}
        with:
          ref: main
      - run: |
          set -e
          git config --global pull.rebase true
          git config --global user.email "github-workflows-@$GITHUB_WORKFLOW-$GITHUB_REPOSITORY"
          git config --global user.name "Github Workflows ($GITHUB_WORKFLOW $GITHUB_REPOSITORY)"
          git remote add upstream https://github.com/XenitAB/azure-devops-templates
          git pull upstream main
          git push origin main
          git fetch upstream --tags --prune
          git push origin --tags refs/remotes/upstream/*:refs/heads/* --prune
